blank_issues_enabled: true
contact_links:
  - name: Bitcoil Core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Bitcoil Core Developers
    url: https://bitcoincore.org
    about: Bitcoil Core homepage
